
--CREATE TABLE CHILD_TBL (
--    ID INT IDENTITY(1,1) NOT NULL,
--    fName VARCHAR(30) NOT NULL,
--    lName VARCHAR(30) NOT NULL,
--    dateOfBirth DATETIME NOT NULL,
--    guardianFName VARCHAR(30) NOT NULL,
--    guardianLName VARCHAR(30) NOT NULL,
--    address VARCHAR(40) NOT NULL,
--	address2 VARCHAR(15) NULL,
--    city VARCHAR(30) NOT NULL,
--    state VARCHAR(2) NOT NULL,
--    zip INT NOT NULL,
--    phone VARCHAR(14) NOT NULL,
--    eMail VARCHAR(50) NULL,
--    emContactName VARCHAR(60) NOT NULL,
--    emContactPhone VARCHAR(14) NOT NULL
--);

INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Katell','Chapman','2011-10-19','Kirby','Flores','1978 Rutrum Street','Queenstown','Rangiora','SI','','(357) 911-8723','neque.venenatis.lacus@sociisnatoquepenatibus.net','Rebekah E. Mays','(306) 322-4859');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Yasir','Elliott','2007-05-07','Britanney','Phelps','3491 Accumsan Ave','Santa Cruz de Tenerife','San Cristóbal de la Laguna','Canarias','','(855) 170-8299','habitant.morbi@sed.co.uk','Kylynn Z. Hardin','(702) 252-4695');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Hedda','Mccormick','2009-10-08','Jack','Welch','Ap #162-7180 Mi. Road','Norman','Norman','Oklahoma','','(869) 429-9687','ac.libero.nec@enim.ca','Price E. Davis','(233) 779-1695');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Aubrey','Frank','2010-03-13','Phoebe','Downs','Ap #306-7923 At, St.','Lienz','Hall in Tirol','Ti','','(534) 498-4200','erat.eget@sagittisaugueeu.edu','Jamal K. Wilder','(849) 452-1772');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Harding','Flynn','2014-02-06','Pamela','Noel','951-6398 Natoque Ave','Rochester','Bloomington','MN','','(100) 149-4430','augue.malesuada.malesuada@esttemporbibendum.net','Brynn V. Hopper','(183) 426-1898');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Evangeline','Payne','2014-05-02','Hilel','Cantrell','191-4701 Ac Street','Palmerston','Darwin','NT','','(123) 105-9579','vehicula@fringillaornare.net','Channing Q. Melendez','(712) 649-0563');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Chadwick','Arnold','2013-11-19','Mannix','Burke','P.O. Box 693, 4107 Sed Road','Fairbanks','Anchorage','Alaska','','(432) 598-2009','enim.nisl@habitantmorbitristique.ca','Dustin L. Bright','(123) 244-8591');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ila','Simon','2006-08-24','Lucius','Singleton','P.O. Box 179, 2670 Amet Av.','Uppingham. Cottesmore','Oakham','Rutland','','(697) 613-2721','quis.arcu@Phasellus.org','Amal A. Adams','(575) 914-6034');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Thane','Dawson','2007-12-04','Caleb','Tucker','Ap #823-6271 Curae; Rd.','Oudergem','Evere','Brussels Hoofdstedelijk Gewest','','(822) 956-1931','Phasellus@pellentesquemassalobortis.net','Keely V. Schwartz','(546) 648-8314');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Willa','West','2012-03-23','Madison','George','P.O. Box 831, 5894 Enim. Avenue','Dallas','Houston','Texas','','(934) 789-4532','convallis.erat@ametconsectetuer.ca','Finn L. Shields','(512) 201-7426');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Barry','Riley','2007-03-30','Shelly','Lynn','3665 Faucibus Avenue','Wagga Wagga','Parramatta','NS','','(191) 527-1396','eu.dui.Cum@Cras.com','Perry B. Wooten','(825) 326-0012');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Louis','Castillo','2008-07-08','Joan','Payne','349-1336 Felis Rd.','Cáceres','Badajoz','Extremadura','','(433) 233-9591','nisi.dictum.augue@enim.net','Imogene S. Williams','(116) 777-2427');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Louis','Moon','2007-04-13','Quinn','Barker','P.O. Box 744, 904 Non Rd.','Mulhouse','Haguenau','Al','','(848) 181-7666','facilisis.facilisis.magna@ataugueid.co.uk','Gavin V. Hodge','(885) 841-6470');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Richard','Spence','2013-07-25','Erich','Head','105-9089 Blandit Rd.','Havr','Buzet','HE','','(287) 762-8266','Class.aptent@parturient.ca','Avye C. Lindsay','(863) 341-6881');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Yuli','Short','2012-10-08','Maggie','Odonnell','6350 Aenean Avenue','Hallein','Salzburg','Salzburg','','(557) 165-7091','ante@facilisis.ca','Denton R. Vance','(654) 694-4519');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Flavia','Shaw','2011-03-22','Ryan','George','Ap #361-859 Auctor, St.','Fortaleza','Sobral','CE','','(693) 569-1040','Quisque.ornare@euenim.net','Chester J. Moreno','(326) 464-1911');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Nell','Bowman','2009-12-17','Alexandra','Reeves','245-7618 Commodo Avenue','Hamburg','Hamburg','HH','','(681) 807-2614','dui.semper@enimNunc.net','Susan G. Church','(572) 143-0299');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Maryam','Floyd','2006-09-04','Aurora','Duffy','P.O. Box 614, 1525 Malesuada Avenue','Melilla','Melilla','ME','','(634) 677-7976','a.nunc@insodales.net','Ezra S. Sears','(903) 676-7906');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Daphne','Cantrell','2013-12-27','Cheyenne','Macdonald','141-2597 Mauris Av.','Berbroek','Mechelen-aan-de-Maas','Limburg','','(179) 779-3861','magna.et@sapien.com','Demetria B. Burch','(993) 415-6754');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Leila','Roman','2010-05-20','Robin','Mcknight','Ap #231-9931 Amet St.','Santa Rita','Cajazeiras','PB','','(654) 800-4546','Duis@sodalesnisimagna.co.uk','Sawyer N. Macias','(257) 715-5765');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Fallon','Wooten','2009-11-08','Joelle','Walters','5986 Lorem Ave','Juazeiro do Norte','Fortaleza','Ceará','','(661) 286-8574','sodales@lorem.co.uk','Scott Y. Dunlap','(227) 621-5706');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Barbara','Sanford','2009-10-17','Sigourney','Knight','Ap #601-2392 Pede Street','León','Soria','CL','','(481) 609-1306','pellentesque@ornaresagittis.co.uk','Martena J. Malone','(176) 284-0333');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ashton','Mcpherson','2010-10-12','Silas','Perez','9322 Maecenas Street','Moere','Snaaskerke','WV','','(897) 491-6306','Maecenas.malesuada.fringilla@eu.com','Blossom H. Holloway','(220) 310-9070');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Whoopi','Cooley','2009-08-06','Shaeleigh','Arnold','218-4622 Nonummy Ave','Devonport','Burnie','TA','','(728) 941-9730','consectetuer.rhoncus.Nullam@elitEtiamlaoreet.ca','Ira T. Santos','(962) 554-3620');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Nell','Boone','2008-05-08','Leah','Ortega','5369 Non Avenue','Castelló','Elx','Comunitat Valenciana','','(363) 801-6078','dignissim.lacus@eutempor.co.uk','Lysandra Z. Walls','(146) 693-7505');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Erin','Soto','2009-08-09','Mason','Vasquez','2964 Fringilla Rd.','Kawawachikamach','Chambord','Quebec','','(362) 637-7915','consectetuer@euismodenimEtiam.com','Jaime J. Buchanan','(943) 916-8856');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Hillary','Barron','2008-04-16','Marvin','Juarez','P.O. Box 184, 888 Porta Rd.','Burgos','Burgos','CL','','(240) 670-7385','magnis.dis.parturient@SuspendisseeleifendCras.org','Nita P. Kirk','(195) 235-8834');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Shelly','Herman','2010-05-16','Jerome','Marsh','Ap #884-6027 Risus. St.','Minitonas','Lourdes','Manitoba','','(821) 705-1907','ornare.lectus.ante@hendreritneque.ca','Wynne R. Rowland','(566) 550-9000');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Brielle','Glenn','2009-05-04','Dacey','Barry','Ap #895-5313 Imperdiet Rd.','Couthuin','Bo','Luik','','(359) 124-5346','blandit.at@egetdictum.com','Wing Z. Guerra','(353) 766-9795');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Kyle','Burks','2014-02-07','Zephania','Anderson','Ap #178-6170 Posuere Road','Parla','Móstoles','Madrid','','(709) 735-0026','ut@Phaselluselit.com','Inga V. Patel','(874) 535-4328');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Leah','Joyner','2011-05-26','Haley','Anderson','9762 Ac St.','Delitzsch','Zittau','Saxony','','(633) 276-4557','consequat@Donec.org','Skyler T. Head','(657) 572-9131');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Cody','Shepherd','2014-05-01','Thomas','Greene','P.O. Box 718, 1097 Molestie Road','Naarden','Schagen','Noord Holland','','(828) 401-3145','Integer.id@Seddiamlorem.edu','Colorado G. Hicks','(480) 208-0413');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Perry','Guzman','2013-06-22','MacKenzie','Buckner','Ap #662-2241 Scelerisque Av.','Nova Iguaçu','Campos dos Goytacazes','Rio de Janeiro','','(463) 553-9776','Duis.sit@In.ca','Brady Y. Todd','(427) 391-9057');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Jenette','Buckley','2009-12-22','Inga','Britt','506-2139 Quis Ave','Leersum','Amersfoort','U.','','(431) 858-1500','Quisque.fringilla@antedictumcursus.ca','Rylee M. Conner','(278) 819-2269');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Brenna','Pennington','2009-11-04','Signe','Forbes','866-8263 Dignissim. Ave','Vernon','Évreux','Up','','(276) 469-6382','elit.Aliquam@Vivamus.com','Allegra L. Wise','(956) 963-8975');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Rachel','Zimmerman','2013-01-01','Peter','Rich','P.O. Box 343, 6785 Duis Ave','Baden-Baden','Pforzheim','Baden','','(522) 228-4072','Fusce.mollis@necimperdietnec.co.uk','Baker Y. Wood','(196) 366-0497');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ray','Guerra','2013-07-09','Katelyn','Mccormick','Ap #397-3443 Sodales Road','Charleville-Mézières','Reims','Ch','','(720) 196-1358','egestas.lacinia.Sed@ultrices.edu','Whitney V. Vasquez','(545) 729-2826');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Daryl','Dominguez','2009-06-03','Acton','Wright','P.O. Box 556, 7561 Cras Av.','Northumberland','Quinte West','Ontario','','(992) 565-4937','velit.justo@imperdietdictum.com','Deborah L. Mcgee','(128) 250-1560');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Nigel','Ward','2011-12-07','Jasmine','Foreman','584 Volutpat. Av.','Herstappe','Paal','L.','','(244) 273-3235','massa.rutrum.magna@consequatenim.edu','Fatima G. Blevins','(420) 897-8407');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Clark','Acosta','2007-12-30','Vernon','Morales','Ap #464-5926 Praesent Street','Sioux City','Davenport','IA','','(944) 913-3106','metus@Ut.edu','Mallory P. Morales','(505) 925-8970');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Dominique','Gregory','2013-06-06','Anne','Stark','807-4064 Nibh. St.','Bremen','Bremerhaven','Bremen','','(163) 779-9454','turpis.non@semper.edu','Amery T. Lara','(974) 408-4975');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Kimberly','Sosa','2012-07-25','Xyla','Porter','4244 Curabitur St.','Cras-Avernas','Herstal','LU','','(871) 412-2619','dui@utmolestie.co.uk','Martin A. Knight','(571) 856-6535');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Hyacinth','Brennan','2008-09-14','Orla','Macdonald','P.O. Box 599, 1655 Tristique Avenue','Horsham','Swan Hill','Victoria','','(926) 974-0597','sed@ac.com','Dorothy S. Sawyer','(205) 346-0979');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Timothy','Deleon','2009-10-06','Daquan','Wilkinson','Ap #127-7910 Sem Street','Roosendaal','Grave','N.','','(889) 166-2625','feugiat@interdumenim.net','Maite Z. Bryant','(804) 697-8950');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Shellie','Reyes','2013-06-28','Adria','Walters','P.O. Box 492, 4319 Cras Rd.','Slough','Buckingham','BK','','(290) 168-0196','Pellentesque.ut.ipsum@Aenean.net','Lester F. Casey','(490) 777-7624');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Chaney','Christensen','2010-08-24','Faith','Gibbs','P.O. Box 478, 4457 Nisl. Ave','Iowa City','Sioux City','IA','','(922) 746-4142','amet.massa.Quisque@odio.edu','Coby S. Guerrero','(842) 663-8975');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Len','Bradley','2007-07-20','Angela','Flowers','Ap #540-1682 Maecenas Rd.','Joinville','Criciúma','Santa Catarina','','(831) 693-8952','tempus@adipiscing.net','Aretha L. Collins','(773) 534-5630');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Joel','Bean','2011-10-09','Dean','Perez','1179 Phasellus Ave','Kapiti','Dannevirke','North Island','','(582) 960-3037','Integer.aliquam@elit.edu','Yoshio D. Sanchez','(218) 382-3005');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Heidi','Lindsey','2011-11-10','MacKensie','Lewis','Ap #743-5680 Et Road','Hengelo','Deventer','Ov','','(503) 744-7925','arcu.Vestibulum@vel.co.uk','Kermit N. Moran','(909) 944-5999');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Shaeleigh','Christensen','2008-09-21','Jonas','Jennings','P.O. Box 629, 9653 Facilisis St.','Coevorden','Hoogeveen','Dr','','(258) 604-5031','dolor.dapibus.gravida@in.net','Christine F. Nichols','(887) 269-6106');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Stewart','Delaney','2012-01-30','Adena','Gonzalez','P.O. Box 334, 865 Et St.','Brechin','Kirriemuir','AN','','(801) 608-7040','sed.facilisis.vitae@atpede.ca','Isadora M. Wilcox','(917) 700-6309');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Yael','Barnett','2012-01-13','Ingrid','Ward','P.O. Box 367, 1071 Dapibus Road','Bungay','Lowestoft','SF','','(137) 446-7760','Nullam@cursusinhendrerit.co.uk','Gil G. Blackburn','(927) 927-3137');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Riley','Parker','2011-01-11','Neville','Stone','P.O. Box 754, 4986 Duis Rd.','Itajaí','Florianópolis','SC','','(358) 585-6439','Quisque.tincidunt@ridiculusmusDonec.org','Chastity J. Rasmussen','(792) 179-7693');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Darius','Hobbs','2010-09-06','Mari','Daniel','4743 Elit. Ave','Nancy','Nancy','Lorraine','','(102) 481-6895','tellus.Phasellus@Utnec.org','Beck M. Stephens','(350) 372-6444');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Erasmus','Patrick','2008-03-03','Savannah','Velazquez','339-7191 Aliquet Av.','Richmond','Midway','British Columbia','','(852) 870-1456','non.justo.Proin@et.net','Kaseem G. Villarreal','(824) 151-8437');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Dennis','Ellis','2007-10-20','Cally','Byrd','6219 Suspendisse St.','Wolfsburg','L','NI','','(788) 513-5644','vitae@mi.com','Kendall K. Maxwell','(302) 954-2761');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Alexa','French','2008-02-27','Brady','Cantrell','Ap #868-8046 Mauris. Road','Canberra','Canberra','Australian Capital Territories','','(980) 945-1112','fermentum.metus.Aenean@dictum.edu','Minerva N. Mcleod','(626) 929-1325');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Steel','Hayden','2009-02-01','Stephanie','Avila','553-6612 Penatibus Avenue','Vitória da Conquista','Camaçari','Bahia','','(406) 162-6886','metus@etrutrumeu.edu','Drew G. Mathis','(652) 946-8418');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Quinlan','Daugherty','2007-11-16','Edan','Henderson','P.O. Box 860, 3028 Consectetuer St.','Aulnay-sous-Bois','Colombes','Île-de-France','','(445) 198-0348','diam.at.pretium@arcuVestibulumut.com','Cassidy Z. Nixon','(473) 755-0991');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Evangeline','Hopper','2011-07-13','Finn','Velasquez','P.O. Box 361, 5624 Consequat Av.','Macduff','Buckie','Banffshire','','(263) 549-1480','gravida.non@vitaenibhDonec.ca','Winifred E. Collins','(107) 632-9238');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Tyler','Burris','2009-05-16','Cameran','Brooks','P.O. Box 169, 8414 Eu Street','Maidenhead','Reading','BR','','(527) 865-2299','lacinia.at@ornare.com','Lester U. Gross','(913) 204-3175');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Sawyer','Mays','2011-05-21','Minerva','Copeland','753-8648 Maecenas Ave','Kaneohe','Kailua','HI','','(412) 697-8827','urna.justo.faucibus@erat.edu','Clarke V. Rogers','(131) 226-8404');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Bruno','Stevens','2009-11-19','Davis','Waters','P.O. Box 173, 8599 Lacus. Rd.','Newport News','Chesapeake','VA','','(782) 830-6726','Lorem@necante.ca','Griffith Z. Dickson','(126) 535-8344');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Jescie','Conner','2012-09-29','Ramona','Hull','P.O. Box 857, 3691 Molestie St.','Wommelgem','Lier','AN','','(666) 100-6310','non.lorem.vitae@dictummagnaUt.net','Jerome Y. Hurst','(437) 979-6226');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Phelan','Patel','2008-11-01','Colette','Vang','P.O. Box 714, 7679 Venenatis St.','Cajazeiras','Santa Rita','PB','','(712) 755-5435','lectus@ipsumdolorsit.co.uk','Sylvia Y. Sexton','(650) 527-6258');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Emily','Finley','2013-05-17','Paloma','Russo','Ap #252-3008 Varius. Road','Manchester','Manchester','Lancashire','','(502) 152-5892','dui@parturient.net','Patrick A. Guthrie','(619) 941-7250');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Kennan','Baker','2013-03-17','Berk','Tucker','P.O. Box 973, 6970 Netus Ave','Girona','Tarrasa','Catalunya','','(514) 775-5488','Ut@sagittis.org','Danielle F. Nunez','(585) 845-9366');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Graiden','Roberson','2008-02-27','Wayne','Mckenzie','P.O. Box 406, 6917 Auctor St.','Wunstorf','Wunstorf','Lower Saxony','','(972) 808-4457','arcu.Nunc@Utnec.net','Porter U. Dean','(830) 568-4225');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ebony','Gay','2009-08-09','Craig','Rollins','Ap #614-8228 Velit St.','Niort','Poitiers','Poitou-Charentes','','(488) 956-3899','hendrerit@In.co.uk','Phillip L. Martinez','(204) 237-3103');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Norman','Grimes','2010-11-22','Dakota','Foster','405-2930 Consectetuer, Ave','Miramichi','Rexton','NB','','(753) 267-8099','eget.tincidunt@cursuset.net','Carl V. Moses','(332) 316-5412');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Paki','Mathews','2007-04-09','Grant','Byrd','Ap #958-1412 Tempor Avenue','Imperatriz','Barra do Corda','Maranhão','','(474) 707-8623','lectus.rutrum.urna@Vivamusmolestiedapibus.edu','Hilda Y. Hoover','(915) 491-7036');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Philip','Rasmussen','2008-09-13','Colleen','Bean','P.O. Box 967, 7407 Ligula Ave','Adelaide','Port Pirie','SA','','(546) 452-7444','sit.amet@vitae.edu','Wynne E. Goodwin','(222) 290-3061');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Uma','Massey','2011-01-23','Ralph','Newman','P.O. Box 585, 9941 Elementum St.','Whithorn','Wigtown','Wigtownshire','','(370) 312-4356','Nullam.suscipit@Vivamusmolestiedapibus.com','Bernard V. Huff','(998) 593-2544');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Yoshi','Chase','2013-03-13','Francis','Holman','836-7220 Eget Street','Moulins','Le Puy-en-Velay','Auvergne','','(329) 963-5685','sodales.at@tincidunttempusrisus.edu','Gabriel M. Lloyd','(614) 815-1553');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Drew','Foster','2011-12-27','Daryl','Meyers','3606 A, Rd.','Donosti','Gasteiz','Euskadi','','(129) 267-3288','ante.ipsum.primis@odioPhasellusat.org','Cedric K. Roach','(408) 281-4174');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Alisa','Lynn','2012-11-05','Serina','Crane','Ap #415-987 Et Street','Prince George','Kent','BC','','(722) 239-6044','pede.nonummy.ut@rhoncus.ca','Lewis E. Whitaker','(815) 410-2344');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('India','Cox','2009-01-08','Savannah','Conrad','9907 Sed Avenue','Hof','Passau','Bavaria','','(681) 596-8170','Aenean.euismod@eleifendnunc.co.uk','Aubrey Z. Booker','(883) 628-7101');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ann','Goodman','2011-08-21','Amery','Mccall','Ap #881-295 Consectetuer St.','Wernigerode','Merseburg','Saxony-Anhalt','','(574) 102-8120','tempor@amet.co.uk','Leonard Q. Chan','(614) 528-5765');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Victor','Robbins','2008-02-01','Kim','Cline','9430 Magna. Road','Sale','Bairnsdale','VI','','(141) 583-3319','eget.nisi.dictum@necluctus.ca','Ocean N. Hurst','(164) 503-2650');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Maxwell','May','2011-02-26','Hilel','Baker','P.O. Box 909, 783 Et Rd.','Darwin','Palmerston','Northern Territory','','(535) 280-2547','elit.a@dictumeueleifend.org','Alexis Q. Delgado','(133) 109-5080');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Raja','Ballard','2012-09-02','Peter','Alexander','Ap #200-819 Iaculis Street','Darwin','Palmerston','Northern Territory','','(724) 750-7848','Duis.mi.enim@nuncQuisque.com','Harlan Z. Wiley','(551) 231-8371');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Jin','Mullen','2006-10-18','Mona','Delgado','P.O. Box 470, 4015 Eu St.','Gosnells','Perth','Western Australia','','(535) 825-3864','nibh@bibendum.ca','Isaiah L. Joseph','(625) 372-9970');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Francesca','Riggs','2008-05-23','Kylynn','Moon','P.O. Box 752, 1492 Quis Street','Terneuzen','Sluis','Zl','','(417) 861-4877','Nunc.ac@PraesentluctusCurabitur.ca','Nolan U. Mccoy','(202) 240-7069');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Mercedes','Morin','2008-09-10','Drake','Cruz','1079 Lectus Avenue','Penrith','Albury','NS','','(283) 324-9309','dictum.eleifend@Duis.co.uk','Tobias E. Garrett','(912) 678-2015');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Ifeoma','Blair','2013-03-20','Jin','Hayden','878-9805 Eget Rd.','Meridian','Idaho Falls','ID','','(489) 311-2338','arcu@Donec.com','Quyn G. Carr','(520) 571-0155');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Jermaine','Flowers','2010-02-02','Audra','Pena','Ap #349-999 Ipsum. Road','Timaru','Alexandra','SI','','(822) 486-7359','vulputate.dui.nec@adipiscing.com','Alea N. Grimes','(850) 793-8712');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Jescie','Mejia','2009-03-14','Charles','Obrien','P.O. Box 516, 740 Tempus Rd.','Bala','Harlech','Merionethshire','','(320) 607-7221','mattis.semper@arcuetpede.edu','Eve M. Daugherty','(297) 944-1106');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('MacKensie','Hampton','2008-10-29','Clayton','Shepard','6759 Commodo Road','Blue Mountains','Blue Mountains','New South Wales','','(320) 531-1668','diam@Utsagittis.edu','Clayton E. Howe','(957) 243-5614');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Sara','Le','2011-03-18','Geraldine','Welch','4351 Dictum Avenue','Mattersburg','Gols','Bg','','(449) 563-6693','at.velit.Pellentesque@orciadipiscingnon.co.uk','Venus B. Underwood','(904) 122-6628');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Chase','Knox','2006-08-31','Brenda','Shaffer','Ap #786-2620 Libero. Rd.','Olinda','Jaboatão dos Guararapes','Pernambuco','','(271) 180-0223','eu.tempor@ridiculusmusDonec.ca','Louis X. Pearson','(620) 145-1296');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Clark','Lane','2013-12-20','Hope','May','Ap #707-9087 Velit Street','Middelburg','Hulst','Zeeland','','(238) 768-7049','egestas@malesuadaut.edu','Karly P. Donaldson','(639) 854-2144');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Gretchen','Silva','2013-02-05','Vivian','Lynn','5816 A, Rd.','Aschaffenburg','Hof','BY','','(114) 979-1836','Mauris.vestibulum@justo.co.uk','Danielle A. Baird','(341) 774-5705');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Vivien','Barron','2014-05-06','Evan','Willis','P.O. Box 531, 2332 Nulla. St.','Leganés','Madrid','Madrid','','(593) 368-8484','magna.nec@malesuadafames.ca','Chester I. Alvarado','(738) 628-9231');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('August','Ewing','2009-01-15','Nash','Erickson','P.O. Box 649, 8522 Libero St.','Cambridge','Taupo','NI','','(687) 510-6580','ligula.eu@tempusmauriserat.edu','Edward V. Sherman','(632) 745-3784');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Kadeem','Haley','2014-02-07','Drew','Lamb','389-4768 Donec St.','Stockerau','Krems an der Donau','Lower Austria','','(609) 246-9834','Cum@arcuAliquamultrices.ca','Chandler C. Calderon','(206) 750-9070');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Josiah','Bird','2010-09-16','Ciaran','Garner','123-3987 Feugiat Rd.','Finkenstein am Faaker See','St. Andrä','Kt','','(555) 667-6342','Phasellus.dolor@pellentesque.ca','Olympia B. Chang','(725) 976-1098');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Charissa','Leonard','2008-11-06','Emily','Key','4008 Imperdiet Rd.','Forbach','Forbach','Lorraine','','(899) 619-3353','Integer@Aliquamadipiscing.edu','Evangeline E. Oneil','(567) 329-8548');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Lysandra','Clemons','2011-07-01','Wing','Ray','9785 Ultricies St.','Greymouth','Gore','SI','','(804) 577-8664','consequat@atvelit.ca','Jolie T. Mercer','(108) 884-0827');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Astra','Bradford','2009-03-23','Xyla','Patton','642-6417 Sapien, Rd.','Mount Pearl','Springdale','Newfoundland and Labrador','','(345) 753-9230','enim@facilisi.ca','Aurora R. Daugherty','(682) 393-2698');
INSERT INTO CHILD_TBL(fName,lName,dateOfBirth,guardianFName,guardianLName,address,address2,city,state,zip,phone,eMail,emContactName,emContactPhone) VALUES('Shay','Mitchell','2007-02-20','Cairo','Smith','P.O. Box 365, 4131 Elit. Street','Doetinchem','Huissen','Gl','','(390) 223-0557','dapibus.ligula@aliquetnecimperdiet.co.uk','Colleen V. Wolf','(451) 537-5259');